steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/cmad-project-sandboxers/cmad_backend_image", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/cmad-project-sandboxers/cmad_backend_image"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'run'
  - 'set'
  - 'deployment/my-deployment'
  - 'my-container=gcr.io/cmad-project-sandboxers/cmad_backend_image'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cmad-cluster'
